apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    github.com/project-slug: sameerijoshi/backstage
spec:
  type: other
  lifecycle: unknown
  owner: sameerijoshi
