apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sample
  title: Sample Template
  description: Example scaffolder template
spec:
  owner: group:default/admins
  type: service
  parameters:
    - title: Name
      type: string
      required: true
  steps:
    - id: fetch
      action: fetch:template
      input:
        url: ./skeleton
